#!/bin/bash -v
sudo -v

## clean download folder
read -pr "Clean Downloads folder? (y/n) " -n 1
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  sudo rm -rfv ~/Downloads/*
fi

## clean desktop folder
read -pr "Clean Desktop folder? (y/n) " -n 1
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  sudo rm -rfv ~/Desktop/*
fi

## clean system data
# clean .DS_Store
sudo find / -name '.DS_Store' -o -name "npm-debug.log" -type f -ls -delete
# clean logs
sudo rm -rfv /Library/Logs/* ~/Library/Logs/*
# clean temps
tempFiles=("/tmp/" "$HOME/tmp/" "$TMPDIR")
for tempFile in "${tempFiles[@]}"
do
  [ -d "$tempFile" ] && sudo rm -rfv "$tempFile/*"
done

# clean trash
sudo rm -rfv /Volumes/*/.Trashes ~/.Trash