#!/bin/bash -v
sudo -v

## clean download folder
read -p "Clean Downloads folder? (y/n) " -n 1
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  sudo rm -rfv ~/Downloads/*
fi

## clean desktop folder
read -p "Clean Desktop folder? (y/n) " -n 1
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  sudo rm -rfv ~/Desktop/*
fi

## clean system data
# clean .DS_Store
sudo find / -name '.DS_Store' -o -name "npm-debug.log" -type f -ls -delete
# clean logs
sudo rm -rfv /Library/Logs/* ~/Library/Logs/*
# clean temp
sudo rm -rfv /tmp ~/tmp "$TMPDIR"
# clean trash
sudo rm -rfv /Volumes/*/.Trashes ~/.Trash