#!/bin/bash

# open all changed files (that still actually exist) in the editor
# credit: @cowboy
files=()
for f in $(git diff --name-only "$@"); do
  [[ -e "$f" ]] && files=("${files[@]}" "$f")
done
n=${#files[@]}
echo "Opening $n $([[ "$@" ]] || echo "modified ")file$([[ $n != 1 ]] && \
  echo s)${@:+ modified in }$@"
open -a Sublime\ Text "${files[@]}"

unset file
unset n