#!/bin/bash
# TODO: Add -v mode
# Need to improve parameters system, but need time :-(

help(){
  echo " Usage: js2coffeProyect <path> [commands]"
  echo -e "\n Commands:"
  echo -e "\t -d: Delete original js files"
  echo -e "\t -v: Verbose mode"
}

[ $# -lt 1 ] && help && exit 1

if [[ "$2" == "-d" ]]; then
  delete=true
else
  delete=false
fi

for FILE in `find $1 -name "*.js" -type f -o -path './node_modules' -prune -o -path './components' -prune`
do
    if [ -e $FILE ] ; then
        COFFEE=${FILE//.js/.coffee}

        echo "converting ${FILE} to ${COFFEE}"
        js2coffee "$FILE" > "$COFFEE"
    else
        echo "File: {$1} does not exist!"
    fi

    [ "$delete" == true -a "$error" == false ] && rm $FILE
done