#!/bin/bash -v

## MacOSX
sudo softwareupdate -i -a

## brew
cd "$(brew --prefix)"
git fetch origin
git reset --hard origin/master
brew update
brew upgrade
brew cleanup

## npm
# sudo chown -R "$(whoami)" ~/.npm
sudo npm update -g

## cabal
cabal update
cabal install cabal-install --force-reinstalls

## ruby
sudo gem update --system
sudo gem update

## clean system
read -p "System Updated. Clean now? (y/n) " -n 1
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  . clean
fi

# finish
brew doctor