#!/bin/bash -v
sudo -v

## MacOSX
sudo softwareupdate -i -a

## brew
cd "$(brew --prefix)"
git fetch origin
git reset --hard origin/master
brew update
brew upgrade --all
sudo brew cleanup

## npm
npm update -g npm
sudo chown -R "$(whoami)" ~/.npm
sudo chown -R "$(whoami)" /usr/local
sudo npm cache clean
david -g
david update -g

## cabal
cabal update
cabal install cabal-install --force-reinstalls

## rvm
rvm get stable --auto-dotfiles
sudo chown -R $USER: ~/.rvm
rvm use default
rvm repair all
rvm cleanup all

## ruby
sudo gem update --system
sudo gem update
sudo gem cleanup

## zsh
upgrade_oh_my_zsh

# finish
diskutil repairPermissions /
brew doctor
brew prune
read -rp "Fixed problem and press any key... " -n 1

## clean system
read -rp "System Updated. Clean now? (y/n) " -n 1
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  . clean
fi
