#!/bin/bash -v

# brew
## preconditions
git -C "$(brew --repo homebrew/core)" fetch

## ensure that /usr/local is writable
sudo chgrp -R admin /usr/local
sudo chmod -R g+w /usr/local

## update, upgrade and cleanup
brew update
brew upgrade
brew upgrade --cask
brew cleanup

## postconditions
brew doctor
read -rp "Fixed problem and press any key... " -n 1
