#!/bin/bash -v

# npm

## preconditions
npm update -g npm

## repair permissions
sudo chown -R "$(whoami)" ~/.npm
sudo chown -R "$(whoami)" /usr/local

## Update global packages
david -g
david update -g

## clenaup
sudo npm cache clean --force
yarn cache clean --force
